[workspace]
resolver = "3"
members = [
    "completed/hard/*",
    "completed/trivial/*",
    "completed/medium/*",
    "progress/*"
, "libfreuden"]

[workspace.dependencies]
libfreuden = { path = "./libfreuden", package = "libfreuden"}

[profile.release]
debug = true
